# Generated by Django 5.2 on 2025-04-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField()),
                ('categoria', models.CharField(max_length=100)),
                ('status', models.CharField(default='ativo', max_length=20)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=100)),
                ('tipo_usuario', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
