# Generated by Django 5.2 on 2025-04-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='tipo_usuario',
            field=models.CharField(choices=[('AD', 'Admin'), ('AL', 'Aluno')], default='AL', max_length=100),
        ),
        migrations.AlterField(
            model_name='curso',
            name='status',
            field=models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=10),
        ),
        migrations.AlterField(
            model_name='reclamacao',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('R', 'Resolvida')], default='P', max_length=10),
        ),
    ]
